Infoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from unicodedata import name
from django.urls import URLPattern, path

from .views import index, blog, detailedView, user_login, search, register, comment

app_name = 'core'
urlpatterns = [
    path('', index),
    path('blog/', blog, name='blog'),
    path('blog/<str:slug>', detailedView, name='detailed-blog'),
    path('search/', search, name='search'),
    path('login/', user_login, name='login'),
    path('sign-up/', register, name='signup'),
    path('comment/', comment, name='comment')
]

core/models.py
from email.policy import default
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone



# Create your models here.
class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    coverpic = models.ImageField(upload_to='post', blank=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    date = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(choices=STATUS_CHOICE, max_length=10, default='draft')

    def save(self):
        self.date = f"{self.publish.strftime('%B')} {self.publish.strftime('%D').split('/')[1]} 20{self.publish.strftime('%D').split('/')[2]}"
        super(Post, self).save()

    class Meta:
        ordering = ('-publish'),

    def __str__(self) -> str:
        return self.title



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self) -> str:
        return f"{self.message}"

core/forms.py
from django.contrib.auth.models import User  
from django.contrib.auth.forms import UserCreationForm  
from django.core.exceptions import ValidationError  
from django import forms  
 
 
class UserRegisterForm(UserCreationForm):


    username = forms.CharField(label='username', min_length=5, max_length=150)  
    email = forms.EmailField(label='email')  
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)  
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)  
  
    def username_clean(self):  
        username = self.cleaned_data['username'].lower()  
        new = User.objects.filter(username = username)  
        if new.count():  
            raise ValidationError("User Already Exist")  
        return username  
  
    def email_clean(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        if new.count():  
            raise ValidationError(" Email Already Exist")  
        return email  
  
    def clean_password2(self):  
        password1 = self.cleaned_data['password1']  
        password2 = self.cleaned_data['password2']  
  
        if password1 and password2 and password1 != password2:  
            raise ValidationError("Password don't match")  
        return password2  
  
    def save(self, commit = True):  
        user = User.objects.create_user(  
            self.cleaned_data['username'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password1']  
        )  
        return user 

core/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login
from django.contrib import messages

from .forms import UserRegisterForm
from .models import Post, Comment

def index(request):
    posts = Post.objects.all()[:5]
    context = {
        'posts':posts
    }
    return render(request, 'index.html', context)


def blog(request):
    posts = Post.objects.all().order_by('id')
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 4)

    try:
        obj = paginator.page(page)
    except PageNotAnInteger: 
        obj = paginator.page(1)
    except EmptyPage:
        obj = paginator.page(paginator.num_pages)

    context = {
        'posts':obj
    }
    return render(request, 'blog.html', context)

def detailedView(request, slug):
    posts = Post.objects.get(slug=slug)
    comments = Comment.objects.filter(post=posts)
    commentCount = Comment.objects.filter(post=posts).count()
    context = {
        'posts':posts,
        'comments':comments,
        'commentCount':commentCount
    }
    return render(request, 'detailView.html', context)


def search(request):
    if request.method == 'POST':
        search = request.POST['searched']
        posts = Post.objects.filter(title__contains=search)
        return render(request, 'blog.html', {'posts':posts})
    else:
        posts = Post.objects.all()
        return render(request, 'blog.html',{'posts':posts})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user= authenticate(request,username=username, password=password)

        if user is not None:
            form = login(request,user)
            return redirect('/')
        return render(request, 'auth/login.html', {'error':'Invalid Username/Password'})
    return render(request, 'auth/login.html')

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            form.save()
            user = authenticate(request, username=username, password=password)
            if user != None:
                login(request, user)
                return redirect('/')
        return render(request, 'auth/signup.html', {'form': form})
    return render(request, 'auth/signup.html')


def comment(request):
    if request.method == 'POST':
        print('called')
    return render(request, 'detailView.html')

templates/blog.html
{% extends 'main.html' %} 

{% block content %}

<h1
  class="text-3xl font-bold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14"
>
  All Blog
</h1>
<p class="text-lg my-2 leading-7 text-gray-500 dark:text-gray-400">
  A blog created with Django and Tailwind.css
</p>

<form class="group relative" method="POST" action="{% url 'core:search' %}">
  {% csrf_token %}
  <svg width="20" height="20" fill="currentColor" class="absolute left-3 top-1/2 -mt-2.5 text-slate-400 pointer-events-none group-focus-within:text-blue-500" aria-hidden="true">
    <path fill-rule="evenodd" clip-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" />
  </svg>
  <input class="focus:ring-2 focus:ring-blue-500 focus:outline-none appearance-none w-full lg:w-1/4 text-sm leading-6 text-slate-900 placeholder-slate-400 rounded-md py-2 pl-10 ring-1 ring-slate-200 shadow-sm" type="text" aria-label="Filter projects" placeholder="Filter projects..." name="searched">
</form>

{% if posts %}
  {% include 'partials/post.html' %}
{% else %}
  {% include 'partials/404.html' %}
{% endif %}
  {% endblock content %}

templates/detailView.html
{% extends 'main.html' %} 

{% block content %}

<div class="mr-auto">
    <h1 class="my-5 text-3xl font-bold leading-9 tracking-tight text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14">
  {{ posts.title }}
</h1>
{% if posts.coverpic %}
<div class="">
    <img class="object-center" src={{posts.coverpic.url}}>
</div>
{% endif %}

<p class="text-lg my-2 leading-7 text-gray-400 my-20">
  {{posts.body}}
</p>
</div>


<hr class="text-white">

<form action="" method="POST">
{% csrf_token %}
  <input class="my-3 w-full rounded-full py-3 text-center focus:outline-cyan-500" type="submit" placeholder="Enter comment..."/>
  <!-- <button type="submit"></button> -->
</form>


<h1 class="text-white text-bold text-2xl mt-2">Comment ({{commentCount}})</h1>

{% for comment in comments %}
<h1 class="text-white text-semibold">
  {{ comment }}
</h1>
{% endfor %}
{% endblock content %}

templates/index.html
{% extends 'main.html' %} 

{% block content %}

<h1
  class="text-3xl font-bold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14"
>
  Latest
</h1>
<p class="text-lg my-2 leading-7 text-gray-500 dark:text-gray-400">
  A blog created with Django and Tailwind.css
</p>

{% include 'partials/post.html' %}
<div class="flex justify-end mr-3">on>
  <a href="{% url 'core:blog' %}">
    <button class="text-gray-100 bg-gradient-to-r from-blue-500 to-cyan-500  rounded-full p-2 px-5 flex uppercase">All blogs
  </a>
      <span><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
        </svg></span>
  </button>
</div>
{% endblock content %}

templates/main.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <title>InfoBlog</title>
    <body class="container mx-auto bg-gray-900">
        {% include 'partials/navbar.html' %}
        <div class="mt-10 ml-10">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="flex justify-center">
            {% include 'partials/footer.html' %}
        </div>
    </body>
</html>

templates/partials/footer.html
<footer class="bottom-0 mx-auto">
  <div class="flex flex-col items-center mt-16">
    <div class="flex mb-3 space-x-4">
      <a
        class="text-sm text-gray-500 transition hover:text-gray-600"
        target="_blank"
        rel="noopener noreferrer"
        href="mailto:vk2345732@gmail.com"
        >
        <span class="sr-only">mail</span>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 20 20"
          class="fill-current text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400 h-6 w-6"
        >
          <path
            d="M2.003 5.884 10 9.882l7.997-3.998A2 2 0 0 0 16 4H4a2 2 0 0 0-1.997 1.884z"
          ></path>
          <path
            d="m18 8.118-8 4-8-4V14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8.118z"
          ></path></svg></a>
          
        <a
        class="text-sm text-gray-500 transition hover:text-gray-600"
        target="_blank"
        rel="noopener noreferrer"
        href="https://github.com/VishDroid-dev">
        <span class="sr-only">github</span>
        <svg
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
          class="fill-current text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400 h-6 w-6"
        >
          <path
            d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"
          ></path></svg></a>
          <a
        class="text-sm text-gray-500 transition hover:text-gray-600"
        target="_blank"
        rel="noopener noreferrer"
        href="https://facebook.com"
        >
        <span class="sr-only">facebook</span
        >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          class="fill-current text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400 h-6 w-6"
        >
          <path
            d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"
          ></path></svg></a
      >
      <a
        class="text-sm text-gray-500 transition hover:text-gray-600"
        target="_blank"
        rel="noopener noreferrer"
        href="https://youtube.com"
        >
        <span class="sr-only">youtube</span
        >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          class="fill-current text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400 h-6 w-6"
        >
          <path
            d="M23.499 6.203a3.008 3.008 0 0 0-2.089-2.089c-1.87-.501-9.4-.501-9.4-.501s-7.509-.01-9.399.501a3.008 3.008 0 0 0-2.088 2.09A31.258 31.26 0 0 0 0 12.01a31.258 31.26 0 0 0 .523 5.785 3.008 3.008 0 0 0 2.088 2.089c1.869.502 9.4.502 9.4.502s7.508 0 9.399-.502a3.008 3.008 0 0 0 2.089-2.09 31.258 31.26 0 0 0 .5-5.784 31.258 31.26 0 0 0-.5-5.808zm-13.891 9.4V8.407l6.266 3.604z"
          ></path></svg></a
      >
      <a
        class="text-sm text-gray-500 transition hover:text-gray-600"
        target="_blank"
        rel="noopener noreferrer"
        href="https://www.linkedin.com/in/vishnu-kannan-4032b1190/"
        >
        <span class="sr-only">linkedin</span
        >
        <svg
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
          class="fill-current text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400 h-6 w-6"
        >
          <path
            d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 0 1-2.063-2.065 2.064 2.064 0 1 1 2.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"
          ></path></svg></a
      >
      <a
        class="text-sm text-gray-500 transition hover:text-gray-600"
        target="_blank"
        rel="noopener noreferrer"
        href="https://twitter.com/Twitter"
        >
        <span class="sr-only">twitter</span
        >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          class="fill-current text-gray-700 dark:text-gray-200 hover:text-blue-500 dark:hover:text-blue-400 h-6 w-6"
        >
          <path
            d="M23.953 4.57a10 10 0 0 1-2.825.775 4.958 4.958 0 0 0 2.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 0 0-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 0 0-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 0 1-2.228-.616v.06a4.923 4.923 0 0 0 3.946 4.827 4.996 4.996 0 0 1-2.212.085 4.936 4.936 0 0 0 4.604 3.417 9.867 9.867 0 0 1-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 0 0 7.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0 0 24 4.59z"
          ></path></svg>
    </a>
    </div>
    <div class="flex mb-2 space-x-2 text-sm text-gray-500 dark:text-gray-400">
      <div>Vishnu Kannan</div>
      <div>•</div>
      <div>© 2022</div>
      <div>•</div>
      <a href="/">InFoBlog for suvit</a>
    </div>
    <div class="mb-8 text-sm text-gray-500 dark:text-gray-400">
      <h1>Made with love</h1>
    </div>
  </div>
</footer>

templates/partials/navbar.html
<nav class="p-6 flex">
        <a class="flex space-x-4" href="/">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="344.564 330.278 111.737 91.218" width="53.87" height="43.61"><defs><linearGradient id="logo_svg__b" gradientUnits="userSpaceOnUse" x1="420.97" y1="331.28" x2="420.97" y2="418.5"><stop style="stop-color:#06b6d4;stop-opacity:1" offset="0%"></stop><stop style="stop-color:#67e8f9;stop-opacity:1" offset="100%"></stop></linearGradient><linearGradient id="logo_svg__d" gradientUnits="userSpaceOnUse" x1="377.89" y1="331.28" x2="377.89" y2="418.5"><stop style="stop-color:#06b6d4;stop-opacity:1" offset="0%"></stop><stop style="stop-color:#67e8f9;stop-opacity:1" offset="100%"></stop></linearGradient><path d="M453.3 331.28v28.57l-64.66 58.65v-30.08l64.66-57.14Z" id="logo_svg__a"></path><path d="M410.23 331.28v28.57l-64.67 58.65v-30.08l64.67-57.14Z" id="logo_svg__c"></path></defs><use xlink:href="#logo_svg__a" fill="url(#logo_svg__b)"></use><use xlink:href="#logo_svg__c" fill="url(#logo_svg__d)"></use></svg>
            <h1 class="text-3xl text-gray-100">InfoBlog</h1>
        </a>

    <div class="hidden sm:flex ml-auto space-x-4">
        <a href="{% url 'core:blog' %}">
            <button class="p-1 font-medium text-gray-100 sm:p-4 uppercase hover:text-cyan-500">Blog</button>
        </a>
        <button class="p-1 font-medium sm:p-4 text-gray-100 uppercase hover:text-cyan-500">Post</button>
        <button class="p-1 font-medium sm:p-4 text-gray-100 uppercase hover:text-cyan-500">Contact</button>
        {% if not user.is_authenticated %}
        <a href="{% url 'core:login' %}">
            <button class="p-1 font-medium text-gray-100 sm:p-4 uppercase hover:text-cyan-500">login</button>
        </a>
        <button class="p-1 font-medium  sm:p-4 text-gray-100 uppercase hover:text-cyan-500">register</button>
        {% else %}
        <button class="p-1 font-medium  sm:p-4 text-gray-100 uppercase hover:text-cyan-500">Create Blog</button>
        {% endif %}
    </div>

        <div class="md:hidden flex items-center ml-auto">
            <button class="outline-none mobile-menu-button">
                <svg
                    class="w-6 h-6 text-gray-500"
                    x-show="!showMenu"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                <path d="M4 6h16M4 12h16M4 18h16"></path>
                </svg>
            </button>
    </div>

    <div class="hidden mobile-menu md:hidden">
        <ul class="absolute top-20 right-0 h-full space-y-10">
            <li class="active">
                <a href="/" class="block px-2 py-4 text-gray-100 bg-black font-semibold">Home</a></li>
            <li>
                <a href="{% url 'core:blog' %}" class="block px-2 py-4 text-gray-100 bg-black font-semibold transition duration-300">All Blogs</a></li>
            <li>
                <a href="#about" class="block px-2 py-4 text-gray-100 bg-black font-semibold transition duration-300">About</a></li>
            <li>
                <a href="#contact" class="block px-2 py-4 text-gray-100 bg-black font-semibold transition duration-300">Contact Us</a></li>
        </ul>
    </div>
</nav>

<script>
	// Grab HTML Elements
	const btn = document.querySelector("button.mobile-menu-button");
	const menu = document.querySelector(".mobile-menu");

	// Add Event Listeners
	btn.addEventListener("click", () => {
	menu.classList.toggle("hidden");
	});
</script>

templates/partials/post.html
<ul class="divide-y divide-gray-700 w-full mx-auto md:px-20">
    {% for post in posts %}
      {% if post.status == 'published' %}
      <li class="py-12">
      <article>
          <dl>
              <dt class="sr-only">Published on</dt>
              <dd class="text-base font-medium leading-6 text-gray-500 text-gray-400">
                  <time datetime="2021-08-07T15:32:14.000Z">{{ post.date }}</time>
              </dd>
          </dl>
          <h2 class="text-2xl font-bold leading-8 tracking-tight my-3">
              <a class="text-gray-100" href="#">{{ post.title }}</a>
          </h2>
          <div class="prose max-w-none text-gray-400 my-3">{{ post.body }}</div>
          <a href="/blog/{{post.slug}}">
            <button class="text-gray-100 bg-gradient-to-r from-blue-500 to-cyan-500  rounded-full p-2 flex">Read more
              <span><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg></span>
          </button>
        </a>
      </article>
    </li>
    {% endif %}
    {% endfor %}
  </ul>
  {% if posts.has_other_pages %}
    <ul class="flex justify-center text-white border-white space-x-10 text-2xl">
      {% if posts.has_previous %}
        <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}
          <li class="active"><span class="border border-blue text-gray-100 px-2">{{ i }} <span class="sr-only  class="border border-blue text-gray-100 px-2"">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if posts.has_next %}
        <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
    {% endif %}